language: go

go:
- 1.13.x

dist: xenial

sudo: required

addons:
  mariadb: '10.4'

services:
  - mariadb

before_install:
  - mysql -u root -e 'CREATE DATABASE workday;'
  - mysql -u root -e "CREATE USER 'workday'@'%' IDENTIFIED BY 'workday';"
  - mysql -u root -e "GRANT ALL ON workday.* TO 'workday'@'%'; FLUSH PRIVILEGES;"

install:
  - go get github.com/magefile/mage
  - mage build

before_script:
  - npm install -i pm2

script:
  - mage test
