language: go
go:
  - 1.13.x
  - master

dist: bionic
sudo: required
addons:
  mariadb: '10.1'

services:
- mariadb

before_install:
- sudo apt-get -y install npm
- npm install pm2@latest -g

install:
- go get github.com/magefile/mage
- mage build

before_script:
- mysql -u root -e 'CREATE DATABASE workday;'
- mysql -u root -e "CREATE USER 'workday'@'%' IDENTIFIED BY 'workday';"
- mysql -u root -e "GRANT ALL ON workday.* TO 'workday'@'%'; FLUSH PRIVILEGES;"

script:
- mage start
- mage test
- mage stop

jobs:
  include:
    - stage: deploy
      script: echo "Deploying to OpenShift"
      services: skip
      before_install: skip
      install: skip
      before_script: skip
      provider: openshift
      server: https://api.us-east-2.starter.openshift-online.com:6443
      project: workday
      app: api
      edge: true # opt in to dpl v2
      on:
        branch: master
      token:
        secure: dQ/DwmYDyJ2JkhUh++II/1QgnIU/TAlobn//zki+G/Id9+Z4XU0DwGHb+WQuxS+RBqASS79imBkzd0b8uZsSgzf8mEFCEbzikZy3rYGJW/CVFVKygbOBRsM7ms+clAEAr9cet6QqKBeRt6WH3AiPfetcNw0GpjKYr0WGdzzq+sf347NRFrhr/rSiOeugBq2EYqtuXeE6tAzm0ivGLl9C4hDYBdkYiQfJ16hk+/hJrwFRZpVv+7yR9J+WphMVqbCrB0XY3qSnwUlgfMw5QdCFvZAqoZbbiIF0OqEDZ+kwSVSPKPZ/zybpyrE+ty83GGuQ3MymMLM35Upr51HB6VNAcwtpwW8Cf3Bzj2odFKzk26etvUDhaPpXMV8Ow9VgYgweEti9KebdM0esN5emr/7vCmLVe3ppNDhH+tfGGmaVM8dkB+L4d2A4kXoxfHyS59HZPGBVFPLmNrxgwxbVaO7EiqUPlBX7SOMMNKn83HUF96edCOXwqVdznfLaG9Uh1/pvfTj4N1NOO1zTdTuuda4WeXSAyWEpgc15RwNQcYp6smtgXk3zFYKA0ZB9C9jyO01Fvoy96H8llY+wrEVuiUmyzSu3KAk6+86SLPJQUHWsvhSTES7qb6c5oSmoBao7X97b4/3EOGHq86wJLE/6vjrqWlrq3BtXpXqiOcbB5el1a9M=
