language: go

go:
- 1.13.x
- master

jobs:
  include:
    - stage: tests coverage
      script: go test -cover -v
      go: 1.13.x

    - stage: Build artifact
      script: go build .

    - stage: Release artifact to GitHub
      deploy:
        provider: releases
        api_key: $WORKDAY_RELEASE
        file: "${GOPATH}/bin/workday"
        skip_cleanup: true
        on:
          tags: true
