- name: Check if go is already installed
  stat:
    path: "/usr/local/bin/go"
  register: go_binary
    
- name: Download Go archive
  get_url:
    url: "https://dl.google.com/go/go{{ GO_VERSION }}.linux-amd64.tar.gz"
    dest: "/tmp/go{{ GO_VERSION }}.linux-amd.tar.gz"
  when: not go_binary.stat.exists 

- name: Unarchive Go archive
  unarchive:
    src: "/tmp/go{{ GO_VERSION }}.linux-amd.tar.gz"
    dest: "/usr/local"
    remote_src: yes
  when: not go_binary.stat.exists
  
- name: Symlink Go binary
  file:
    src: "/usr/local/go/bin/go"
    dest: "/usr/local/bin/go"
    state: link
  when: not go_binary.stat.exists 
