on: push

name: Unit tests

jobs:
  checks:
    name: run
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: run
      uses: cedrickring/golang-action@1.4.1
      env:
        GO111MODULE: "on"
      with:
        args: go build && go test -cover -v
